# Generated by Django 4.2.1 on 2023-05-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movies",
            name="budget",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movies",
            name="cast",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movies",
            name="crew",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movies",
            name="director",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movies",
            name="homepage",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="movies",
            name="index",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movies",
            name="keywords",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="movies",
            name="original_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="movies",
            name="overview",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movies",
            name="popularity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movies",
            name="production_companies",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="movies",
            name="production_countries",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="movies",
            name="release_date",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="movies",
            name="revenue",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movies",
            name="runtime",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movies",
            name="spoken_languages",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="movies",
            name="status",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="movies",
            name="tagline",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movies",
            name="title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="movies",
            name="vote_average",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="movies",
            name="vote_count",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
